project:
  type: website
  output-dir: docs

website:
  title: "[Sena Nur Ensici]'s Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/ensici
      - icon: instagram
        href: https://www.instagram.com/ensici/
      - icon: linkedin
        href: https://www.linkedin.com/in/sena-en%C5%9Fici-b47083176/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: journal
      dark: quartz
    css: styles.css


editor: visual

